### ISSUE TITLE
Option to turn off automatic calculation of con mod for HP

### ISSUE THREAD

**Issue by austen0** [ThaumRystra/DiceCloud1#136]
It would be great to have the option to turn off the feature that automatically calculates the Con mod portion of your hit points. One of my characters' Con score went down recently and changing it in DiceCloud caused his HP to go down because it automatically adjusted the value for already earned levels. I'm just using an effect right now to re-add those points as a workaround but it would be nice to have the option to just manually control HP.

**Comment by Dumbgenius** [comment]
That's how it works in the normal D&D rules - see [the RPG StackExchange](https://rpg.stackexchange.com/questions/94302/are-constitution-changes-retroactive-when-calculating-max-hp):

>If your Constitution modifier changes, your hit point maximum changes as well, as though you had the new modifier from 1st level.

**Comment by austen0** [comment]
Oh ok, I did not realize this. That said, I really like that DiceCloud allows for you set up pretty much all calculations for yourself, so I still think it would be nice to have the option to toggle this feature similar to the encumbrance rules. My DM likes to do a fair amount of house-ruling so the more I can customize the better! Since there are workarounds though, no worries if this request put in low priority or even just closed out.

**Comment by ThaumRystra** [comment]
If this does get changed in the future, it will be for new characters only, and it'll only come as part of a rework of how new characters are created. I don't think there is a lot of value in adding this as an option, since the workaround is as simple as adding a new effect that adds `-constitutionMod * level` to your hitpoints.
