### ISSUE TITLE
Spells added from Library like to delete themselves

### ISSUE THREAD

**Issue by mommothazaz123** [ThaumRystra/DiceCloud1#137]
After adding multiple spells to a character by selecting multiple boxes from the library, all the spells except the first selected one will slowly remove themselves from the sheet.  
https://gyazo.com/1f45f06c3a3ac8eecaf25e5d4e363d10  
Character ID: Lk3hAPxq5L3uZJBfY

**Comment by ThaumRystra** [comment]
I've been able to reproduce this. The spells add themselves locally, but the server denies multiple inserts for some reason. Will fix soon.
