### ISSUE TITLE
vMix JSON export errors

### ISSUE THREAD

**Issue by mommothazaz123** [ThaumRystra/DiceCloud1#140]
1. `"HitDice": "3d8 + +3"` - HitDice field displays plus twice  
2. `"Flaws": "Donâ€™t expect me to save those who canâ€™t save themselves...` - Personality fields seem to have issues encoding unicode  
3. `intelligence` and `intelligenceMod` starts with a lowercase letter while all others start with uppercase  
4. Spell lists are not returned  
5. Resistances/immunities/vulnerabilities are not returned  
6. Skill effects (i.e. always advantage/disadvantage) are not returned  
7. Attack model is inconsistent and not programmatically parsable (perhaps return a list of objects instead, see example below?)  
8. `attackBonus` is not parsed in attacks from spells  

Ex.  
```js
{  
  'name': 'Some Attack',
  'attackBonus': 3,
  'damage': '1d8+3',
  'damageType': 'piercing',
  'effect': 'Versatile (1d8)'
}
```

**Comment by ThaumRystra** [comment]
> 3. Spell lists are not returned

vMix can't parse arrays. What is expected to be returned?

> 7. Attack model is inconsistent and not programmatically parsable

It's not intended to be programmatically parsable, vMix does not have programmatic access to these strings beyond displaying them.

If you are accessing your character through the vMix export functionality for some other purpose, I would strongly advise you not to. The vMix JSON export is very taxing on the server, and programmatically accessing it with any kind of frequency will add a lot of unnecessary load.

**Comment by ThaumRystra** [comment]
This endpoint is for vMix. A video streaming tool. It's incredibly heavy on the server, but only expected to be used for 3 or 4 characters by a small number of users who use vMix.

A general purpose JSON endpoint can be made available as soon as it's viable to do so without crippling the server.

At the moment, the only way to programatically access DiceCloud without adding undue server load is to access DiceCloud through standard Meteor subscriptions, the same way DiceCloud's client does, and computing the character from the raw data similarly to how it's done in the [vMix export code](https://github.com/ThaumRystra/DiceCloud1/blob/master/rpg-docs/lib/functions/characterExport.js)

Can you open a new issue that details your use case a little more clearly? What format you expect the data to be in and how often you expect to be accessing it and over how many characters at a time.

**Comment by mommothazaz123** [comment]
I am currently still using Meteor subscriptions, I was unsure whether I was intended to change to such a protocol or whether one had been made available.

Sorry for any confusion, and thanks for the reply.
