### ISSUE TITLE
Spell attacks still listed in attack list as available when no slots left to cast

### ISSUE THREAD

**Issue by chisaipete** [ThaumRystra/DiceCloud1#17]
I'm guessing that spell slots aren't part of the enabled/disabled check/calculation for attacks which come from spells that require spell slots.

**Comment by ThaumRystra** [comment]
This has gone a little off topic. The attacks in spells were never intended to go much further than a handy way to store cantrip attacks.

Closing this for now, we can open more specific issues regarding improving the stats page and adding in an action section.
