### ISSUE TITLE
DiceCloud will not run locally

### ISSUE THREAD

**Issue by JukeBoxHeroTP** [ThaumRystra/DiceCloud1#176]
I'm having trouble getting this to run locally. I want to contribute to the project, but need it running first. I followed the readme, but end up getting 'your application is crashing'. It says cannot find module 'fibers'. I didn't really want to submit this as an issue as I just need some help getting it working, but I couldn't find a way to just message you. So I apologize if this doesn't belong here.

**Comment by ThaumRystra** [comment]
Issues running the code locally definitely belong here.

try `meteor npm install fibers`. It might be missing from the package.js file, in which case I'll add it and save with the next update.
