### ISSUE TITLE
Include SRD content

### ISSUE THREAD

**Issue by ThaumRystra** [ThaumRystra/DiceCloud1#47]

**Comment by ThaumRystra** [comment]
@chisaipete SRD content is now being included in items, any chance you can use that script to parse the missing items into the JSON format that the others are being stored in and make a pull request?

Looking at spells next

**Comment by chisaipete** [comment]
@ThaumRystra for sure, let me look at it today.

**Comment by chisaipete** [comment]
Okay, I can probably pull this together...but what items actually remain?  I see things like Tools and Mount related things...is that it?

**Comment by ThaumRystra** [comment]
>  I see things like Tools and Mount related things...is that it?

Also coins. I'll look into containers at a later date.

The SRD also has a bunch of magic items, but they are going to take significantly more effort because they come with effects.

**Comment by ThaumRystra** [comment]
Tools and spells are added. Closing this for now. Separate issues can be added for omissions.
