### ISSUE TITLE
Saving Throw and Skills tables out of alignment

### ISSUE THREAD

**Issue by jrens** [ThaumRystra/DiceCloud1#62]
The headers for Saving Throws and Skills are sitting out of place with their tables (assume tables).
![alignment](https://cloud.githubusercontent.com/assets/11200400/25736054/abf5013e-31c3-11e7-8731-ac4e856fb18b.png)

Chrome Version 59.0.3071.29 (Official Build) beta (64-bit)

**Comment by ThaumRystra** [comment]
Chrome loves breaking multi-column layout. 

Procedure here is to find out what changed in the multi-column rendering, figure out how to stop it breaking the layout without also breaking other supported browsers. Chrome 58 is still the stable release, and works well, so we still have some time to fix.

**Comment by ThaumRystra** [comment]
Chrome 59 is now stable, this is now urgent
