### ISSUE TITLE
Cannot make new character!

### ISSUE THREAD

**Issue by mynameiscandyy** [ThaumRystra/DiceCloud1#66]
Whenever i try to add a new character that I'd like to make no matter what it just never adds. I click add and it just closes. I put different names, longer names, shorter names, leaving it blank, or just putting jibberish in every line. Help? Wanna make some new characters.

**Comment by rperce** [comment]
Issue confirmed by one of my players.

**Comment by ThaumRystra** [comment]
Looks like dialog stacks aren't using their results when closing, this will cause an issue with more than just characters. A fix is on the way.
