### ISSUE TITLE
dicecloud.com: The application has stopped working unexpectedly.

### ISSUE THREAD

**Issue by enj** [ThaumRystra/DiceCloud1#69]
@ThaumRystra is the app down?

**Comment by ThaumRystra** [comment]
Not anymore, [reddit post](https://www.reddit.com/r/dicecloud/comments/6bul5q/dicecloud_outage_20170517_1830_20170518_0630/):

> At 18:20 local time yesterday (about 8:00 Pacific standard time) DiceCloud's hosting provider had a brief issue with databases not responding. The issue was resolved in 10 minutes, and the affected containers were reset.
For some reason, DiceCloud did not come back online after the automated reset, and remained out of service for about 12 hours until I could manually restart it.
The notification setup I was using also failed to let me know that DiceCloud was down. Fortunately I was gently poked by a few mentions on Reddit, and some private messages as well, letting me know that the service was out.
I have taken steps to improve monitoring of DiceCloud's service (and notifications of outages) to prevent similar events in the future from taking so long to resolve.
I'm also still investigating why DiceCloud failed to start after the automated reset, but I don't have any answers on that front yet.
I'm really sorry to anyone who had a game yesterday and was left without a character sheet. I can't really make amends, but I can improve the service for the future.

**Comment by enj** [comment]
Thanks @ThaumRystra!
