### ISSUE TITLE
Text overflows titles on small devices

### ISSUE THREAD

**Issue by joshuata** [ThaumRystra/DiceCloud1#90]
The class `paper-font-title` has the property `white-space: nowrap` which causes it to run off the sides of the display on phone sized devices.

**Comment by ThaumRystra** [comment]
Can you give specific instances where this occurs?

It is already noted as happening in the spells tab with spell names or summaries that are too long in #83

**Comment by joshuata** [comment]
The simplest example is the text on the home page that says "Spend less time shuffling paper and more time playing"
