### ISSUE TITLE
Unable to reverse-proxy Dicecloud

### ISSUE THREAD

**Issue by TheFiZi** [ThaumRystra/DiceCloud1#98]
Installed Dicecloud on my own server and configured my existing Apache install to act as a proxy.

When I try to load the page I get "The page isn’t redirecting properly" and "Firefox has detected that the server is redirecting the request for this address in a way that will never complete"

I'm honestly not 100% sure why the proxying isn't working. I'll keep digging but I've used this same configuration multiple times with other services like Sickrage, etc.

Here is my vhost entry:

```
<VirtualHost *:80>
       ServerName dicecloud.myfqdn.com
       DocumentRoot /data/wwwPublic/siteMain
       CustomLog logs/dicecloud.myfqdn.com.log combined
       ErrorLog logs/dicecloud.myfqdn.com-error.log

       RewriteEngine On
       RewriteCond %{SERVER_PORT} 80
       RewriteRule ^(.*)$ https://dicecloud.myfqdn.com$1 [R,L]

</VirtualHost>
<VirtualHost *:443>
        ServerName dicecloud.myfqdn.com
        DocumentRoot /data/wwwPublic/siteMain
        CustomLog logs/dicecloud.myfqdn.com.log combined
        ErrorLog logs/dicecloud.myfqdn.com-error.log

        ProxyRequests Off
        ProxyPreserveHost On

        <Proxy *>
                Order deny,allow
                Allow from all
        </Proxy>

        ProxyPass / http://localhost:3000/
        ProxyPassReverse / http://localhost:3000/

        SSLEngine on
        SSLHonorCipherOrder on
        SSLProtocol all -SSLv2 -SSLv3
        SSLCipherSuite EECDH+ECDSA+AESGCM:EECDH+aRSA+AESGCM:EECDH+ECDSA+SHA384:EECDH+ECDSA+SHA256:EECDH+aRSA+SHA384:EECDH+aRSA+SHA256:EECDH+aRSA+RC4:EECDH:EDH+aRSA:RC4:!aNULL:!eNULL:!LOW:!3DES:!MD5:!EXP:!PSK:!SRP:!DSS:!RC4
        Header always set Strict-Transport-Security "max-age=63072000; includeSubDomains"

        SSLCertificateFile /etc/letsencrypt/live/dicecloud.myfqdn.com/fullchain.pem
        SSLCertificateKeyFile /etc/letsencrypt/live/dicecloud.myfqdn.com/privkey.pem
</VirtualHost>
```

Update 1:

Looks like the proxy request goes through and gets a 301 from Dicecloud and goes into a loop?

![untitled](https://user-images.githubusercontent.com/1762426/28083907-cd628336-662b-11e7-9be9-b1eac8bf9e9a.png)

**Comment by TheFiZi** [comment]
Issue is on my end. Didn't realize this used Websockets. My Apache is to old to proxy those.

**Comment by ThaumRystra** [comment]
Glad you got it sorted; if it helps you can take a look at [Meteor's environmental variables](https://docs.meteor.com/environment-variables.html), you can probably still get it working behind an apache proxy by setting `DISABLE_WEBSOCKETS` and the correct `ROOT_URL`

**Comment by TheFiZi** [comment]
Haven't got it fixed yet but I'll post something if I get it figured out.
